/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package otomasyoncafe;

/**
 *
 * @author Sefa
 */
public class İcecekler extends javax.swing.JFrame {
    AdisyonSefa adisyonsefa =new AdisyonSefa();
    /**
     * Creates new form İcecekler
     */
    public İcecekler() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPnl_icecekler = new javax.swing.JPanel();
        jBtn_cay = new javax.swing.JButton();
        jBtn_kola = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPnl_icecekler.setBackground(new java.awt.Color(153, 255, 153));

        jBtn_cay.setText("ÇAY");
        jBtn_cay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn_cayActionPerformed(evt);
            }
        });

        jBtn_kola.setText("KOLA");

        javax.swing.GroupLayout jPnl_iceceklerLayout = new javax.swing.GroupLayout(jPnl_icecekler);
        jPnl_icecekler.setLayout(jPnl_iceceklerLayout);
        jPnl_iceceklerLayout.setHorizontalGroup(
            jPnl_iceceklerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnl_iceceklerLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jBtn_cay)
                .addGap(26, 26, 26)
                .addComponent(jBtn_kola)
                .addContainerGap(220, Short.MAX_VALUE))
        );
        jPnl_iceceklerLayout.setVerticalGroup(
            jPnl_iceceklerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnl_iceceklerLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPnl_iceceklerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jBtn_cay, javax.swing.GroupLayout.DEFAULT_SIZE, 57, Short.MAX_VALUE)
                    .addComponent(jBtn_kola, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(216, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPnl_icecekler, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPnl_icecekler, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtn_cayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_cayActionPerformed
        
    }//GEN-LAST:event_jBtn_cayActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(İcecekler.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(İcecekler.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(İcecekler.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(İcecekler.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new İcecekler().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtn_cay;
    private javax.swing.JButton jBtn_kola;
    private javax.swing.JPanel jPnl_icecekler;
    // End of variables declaration//GEN-END:variables
}
